import unittest
from HTMLTestRunner import HTMLTestRunner
'''
https://blog.csdn.net/huilan_same/article/details/52944782
https://www.cnblogs.com/feng0815/p/8045850.html
'''

def add(a, b):
    return a+b

def minus(a, b):
    return a-b

def multi(a, b):
    return a*b

def divide(a, b):
    return a/b



class TestMathFunc(unittest.TestCase):
    def setUp(self):
        print("do something before test.Prepare environment.")

    def tearDown(self):
        print("do something after test.Clean up.")

    @classmethod
    def setUpClass(cls):
        print("This setUpClass() method only called once.")

    @ classmethod
    def tearDownClass(cls):
        print("This tearDownClass() method only called once too.")



    def test_add(self):
        """Test method add(a, b)"""
        self.assertEqual(3, add(1, 2))
        self.assertNotEqual(3, add(2, 2))

    @unittest.skip("I don't want to run this case.")
    def test_minus(self):
        """Test method minus(a, b)"""
        self.assertEqual(1, minus(3, 2))

    def test_multi(self):
        """Test method multi(a, b)"""
        self.assertEqual(6, multi(2, 3))

    def test_divide(self):
        """Test method divide(a, b)"""
        self.assertEqual(2, divide(6, 3))
        self.assertEqual(2.5, divide(5,2))

if __name__ == '__main__':
    suite = unittest.TestSuite()

    tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"),TestMathFunc("test_multi"), TestMathFunc("test_divide")]

    suite.addTests(unittest.TestLoader().loadTestsFromModule(tests))

    # runner = unittest.TextTestRunner(verbosity=2)

    with open('HTMLReport.html', 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2)
        # verbosity参数可以控制执行结果的输出，0 是简单报告、1 是一般报告、2 是详细报告。
        runner.run(suite)


